
services:
###########################
# Setup the Apache container
###########################
    httpd:
        container_name: ${NAME_PROJECT}_httpd
        restart: always
        image: httpd:${VALUE_HTTPD_VERSION}
        ports:
            - ${VALUE_HTTPD_PORT}:80
        volumes:
            - ./.docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./.docker/apache/vhosts/:/usr/local/apache2/conf/vhosts
            - ./projecttmp/tmp/httpd/:/usr/local/apache2/tmp/httpd:rw
            - ./projecttmp/log/httpd/:/usr/local/apache2/logs:rw
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        container_name: ${NAME_PROJECT}_php
        restart: always
        build: ./.docker/php/
        volumes:
            - ./www/:/usr/local/apache2/www
            - ./config/config_sgbd.php:/usr/local/apache2/www/config/config_sgbd.php:rw
            - ./projecttmp/log/php:/usr/local/projecttmp/log/php:rw
            - ./projecttmp/log/xdebug:/usr/local/projecttmp/log/xdebug:rw
            - ./projecttmp/tmp/php:/usr/local/projecttmp/tmp/php:rw
            - ./.docker/php/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:ro
            - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
            
###########################
# Setup the Database (MariaDB) container
###########################
    mariadb:
        container_name: ${NAME_PROJECT}_mariadb
        restart: always
        image: mariadb:${VALUE_MARIABD_VERSION}
        volumes:
            - ./projecttmp/log/mysql:/var/log/mysql:rw
            - ./projecttmp/tmp/mysql:/var/tmp/mysql:rw
            - ./projecttmp/mysql_data:/var/lib/mysql
            - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
            - ./.docker/mysql/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:ro
            # start sql
            - ./config/0001_damp.sql:/docker-entrypoint-initdb.d/0001_damp.sql
            # stop sql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            
###########################
# Setup the PhpMyAdmin container
###########################
    myadmin:
        container_name: ${NAME_PROJECT}_phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_PORT=3306
            - PMA_HOST=${NAME_PROJECT}_mariadb
            - PMA_USER=root
            - PMA_PASSWORD=secret
        ports:
            - ${VALUE_PHPMYADMIN_PORT}:80
        depends_on: 
            - mariadb
            
###########################
# Setup the mailhog container
###########################
    mailhog:
        container_name: ${NAME_PROJECT}_mailhog
        restart: always
        image: mailhog/mailhog:${VALUE_MAILHOG_VERSION}
        ports:
            - ${VALUE_MAILHOG_DISPLAY_PORT}:8025
            
