
services:
###########################
# Setup the PHP container
###########################
    php:
        container_name: ${NAME_PROJECT}_php
        restart: always
        build: 
            context: ./.docker/php/
            cache_from:
                - composer:${VALUE_COMPOSER_VERSION}
                - mailhog/mailhog:${VALUE_MAILHOG_VERSION}
            args:
                - VALUE_PHP_VERSION=${VALUE_PHP_VERSION}
                - VALUE_XDEBUG_VERSION=${VALUE_XDEBUG_VERSION}
                - VALUE_GOLANG_VERSION=1.11.8
        volumes:
            - ./www/:/usr/local/apache2/www
            - ./config/config_sgbd.php:/usr/local/apache2/www/config/config_sgbd.php:rw
            - ./config/filedotenv.php:/usr/local/apache2/www/config/filedotenv.php:rw
            - ./.env:/usr/local/apache2/www/config/.env:rw
            - ./.dockertmp/log/php:/usr/local/.dockertmp/log/php:rw
            - ./.dockertmp/log/xdebug:/usr/local/.dockertmp/log/xdebug:rw
            - ./.dockertmp/tmp/php:/usr/local/.dockertmp/tmp/php:rw
            - ./.docker/php/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:ro
            - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
